version: '3.8'
services:
    netcore:
        image: dotnetcore_compose
        ports:
            - 8082:80
        depends_on:
            - mssqlserver

    mssqlserver:
        image: mcr.microsoft.com/mssql/server:latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=!1q2w3e4r5t
        volumes:
            - G:\DockerShared\mssql_netcorecompose_ex:/var/opt/mssql
        ports:
            - 1434:1434